name: either_option
description: The simple library for Error Handling with functionnal programming concept
version: 1.0.0
author: cb yannick <cbyannick@gmail.com>
homepage: https://github.com/cbyad/either_option
repository: https://github.com/cbyad/either_option

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  # flutter:
  #   sdk: flutter

dev_dependencies:
  http: ^0.12.0+2
  flutter_test:
    sdk: flutter
  
  
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
# flutter: 